-- Product dimension table of our small data warehouse.
-- ProductKey is the surrogate key (generated by the database),
-- ProductAltKey is the business key coming from the source system.
DROP TABLE IF EXISTS dbo.DimProduct;
GO

CREATE TABLE dbo.DimProduct(
    ProductKey    INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ProductAltKey NVARCHAR(30) NULL UNIQUE,
    ProductName   NVARCHAR(50) NULL,
    Color         NVARCHAR(30) NULL,
    Size          NVARCHAR(50) NULL,
    ListPrice     MONEY NULL,
    Discontinued  BIT NULL
);
GO

-- One product already exists in the warehouse, the pipeline will update it
INSERT INTO dbo.DimProduct (ProductAltKey, ProductName, Color, Size, ListPrice, Discontinued)
VALUES ('AR-5381', 'Adjustable Race', 'Red', NULL, 1.99, 0);
GO
